// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAuthor(ctx context.Context, username string) (User, error)
	ListAuthors(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
