// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, email, hasshed_password
) VALUES (
  $1, $2, $3
)
RETURNING username, email, hasshed_password, updated_at, created_at
`

type CreateUserParams struct {
	Username        string `json:"username"`
	Email           string `json:"email"`
	HasshedPassword string `json:"hasshed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.HasshedPassword)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.HasshedPassword,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT username, email, hasshed_password, updated_at, created_at FROM users
WHERE username = $1 LIMIT username
`

func (q *Queries) GetAuthor(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.HasshedPassword,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT username, email, hasshed_password, updated_at, created_at FROM users
`

func (q *Queries) ListAuthors(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Username,
			&i.Email,
			&i.HasshedPassword,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
